default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: 127.0.0.1
  port: 5432
  username: pciacka
  password: ~

development:
  <<: *default
  database: checklists_development

test:
  <<: *default
  database: checklists_test

production:
  <<: *default
  database: checklists_production
  username: checklists
  password: <%= ENV['CHECKLISTS_DATABASE_PASSWORD'] %>
