default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV.fetch('APP_DB_HOST', '127.0.0.1') %>
  port: 5432
  username: <%= ENV.fetch('APP_DB_USER', 'postgres') %>
  password: ~

development:
  <<: *default
  database: checklists_development

test:
  <<: *default
  database: checklists_test

production:
  <<: *default
  database: checklists_production
  username: checklists
  password: <%= ENV['CHECKLISTS_DATABASE_PASSWORD'] %>
